server:
  port: ${AI_SERVICE_PORT}

spring:
  data:
    mongodb:
      uri: ${MONGODB_AI_URI}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE}
  queue:
    name: ${RABBITMQ_QUEUE}
  routing:
    key: ${RABBITMQ_ROUTING_KEY}

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}